// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Sanathana.Companion.Infrastructure.Persistence;

#nullable disable

namespace Sanathana.Companion.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260726100012_AddSadhana")]
    partial class AddSadhana
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.Chant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Count")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("HasCount")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Chants_Name");

                    b.ToTable("Chants", (string)null);
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.ChantConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AudioContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AudioFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<long?>("AudioSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ChantId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChantText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeityIds")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<TimeOnly?>("FromTime")
                        .HasColumnType("time without time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TimeDescription")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<TimeOnly?>("ToTime")
                        .HasColumnType("time without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChantId")
                        .HasDatabaseName("IX_ChantConfigs_ChantId");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_ChantConfigs_Name");

                    b.ToTable("ChantConfigs", (string)null);
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.ChantConfigAudio", b =>
                {
                    b.Property<Guid>("ChantConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ChantConfigId");

                    b.ToTable("ChantConfigAudios", (string)null);
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.Day", b =>
                {
                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("DayId");

                    b.ToTable("Days", (string)null);

                    b.HasData(
                        new
                        {
                            DayId = 1,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 1,
                            IsActive = true,
                            Name = "Sunday"
                        },
                        new
                        {
                            DayId = 2,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 2,
                            IsActive = true,
                            Name = "Monday"
                        },
                        new
                        {
                            DayId = 3,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 3,
                            IsActive = true,
                            Name = "Tuesday"
                        },
                        new
                        {
                            DayId = 4,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 4,
                            IsActive = true,
                            Name = "Wednesday"
                        },
                        new
                        {
                            DayId = 5,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 5,
                            IsActive = true,
                            Name = "Thursday"
                        },
                        new
                        {
                            DayId = 6,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 6,
                            IsActive = true,
                            Name = "Friday"
                        },
                        new
                        {
                            DayId = 7,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DisplayOrder = 7,
                            IsActive = true,
                            Name = "Saturday"
                        });
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.Deity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Days")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DeityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Festivals")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("ImageContentType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<byte[]>("ImageData")
                        .HasColumnType("bytea");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Regions")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("WelcomeNote")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Deities_Name");

                    b.ToTable("Deities", (string)null);
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.Festival", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Regions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Year")
                        .HasDatabaseName("IX_Festivals_Year");

                    b.HasIndex("Year", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Festivals_Year_Name");

                    b.ToTable("Festivals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000001"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 1, 14),
                            Description = "Harvest festival marking the sun's transition into Capricorn",
                            IsActive = true,
                            Name = "Makar Sankranti",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000002"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 1, 23),
                            Description = "Worship of Goddess Saraswati, welcoming spring",
                            IsActive = true,
                            Name = "Vasant Panchami",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000003"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 2, 15),
                            Description = "The great night of Lord Shiva",
                            IsActive = true,
                            Name = "Maha Shivaratri",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000004"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 3, 3),
                            Description = "Festival of colours celebrating the triumph of good over evil",
                            IsActive = true,
                            Name = "Holi",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000005"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 3, 19),
                            Description = "Hindu New Year for the Deccan region",
                            IsActive = true,
                            Name = "Ugadi / Gudi Padwa",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000006"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 3, 27),
                            Description = "Birth of Lord Rama",
                            IsActive = true,
                            Name = "Rama Navami",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000007"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 4, 2),
                            Description = "Birth of Lord Hanuman",
                            IsActive = true,
                            Name = "Hanuman Jayanti",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000008"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 7, 29),
                            Description = "Honouring spiritual gurus and teachers",
                            IsActive = true,
                            Name = "Guru Purnima",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000009"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 8, 28),
                            Description = "Celebrating the sacred bond between brothers and sisters",
                            IsActive = true,
                            Name = "Raksha Bandhan",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000010"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 9, 4),
                            Description = "Birth of Lord Krishna",
                            IsActive = true,
                            Name = "Krishna Janmashtami",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000011"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 9, 14),
                            Description = "Birth of Lord Ganesha",
                            IsActive = true,
                            Name = "Ganesh Chaturthi",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000012"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 10, 11),
                            Description = "Nine nights devoted to Goddess Durga",
                            IsActive = true,
                            Name = "Navaratri Begins",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000013"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 10, 20),
                            Description = "Victory of good over evil",
                            IsActive = true,
                            Name = "Dussehra (Vijayadashami)",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000014"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 10, 29),
                            Description = "Fast observed for the well-being of one's spouse",
                            IsActive = true,
                            Name = "Karwa Chauth",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000015"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 11, 8),
                            Description = "Festival of lights",
                            IsActive = true,
                            Name = "Diwali (Deepavali)",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000016"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 11, 10),
                            Description = "Worship of Govardhan Hill",
                            IsActive = true,
                            Name = "Govardhan Puja",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000017"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 11, 11),
                            Description = "Celebrating the bond between brothers and sisters",
                            IsActive = true,
                            Name = "Bhai Dooj",
                            Year = 2026
                        },
                        new
                        {
                            Id = new Guid("fe510000-0000-0000-0000-000000000018"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Date = new DateOnly(2026, 11, 15),
                            Description = "Worship of the Sun God, Surya",
                            IsActive = true,
                            Name = "Chhath Puja",
                            Year = 2026
                        });
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.Language", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NativeName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Regions")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Languages_Name");

                    b.ToTable("Languages", (string)null);
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.MenuModule", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVisibleInMenu")
                        .HasColumnType("boolean");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("RoutePath")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("ShowInMobile")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("IX_MenuModules_ParentId");

                    b.ToTable("MenuModules", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Home dashboard",
                            DisplayOrder = 1,
                            Icon = "🕉️",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Dashboard",
                            RoutePath = "/",
                            ShowInMobile = true
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Master data & configuration",
                            DisplayOrder = 2,
                            Icon = "🗂️",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Masters",
                            ShowInMobile = false
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage modules & sub-modules",
                            DisplayOrder = 1,
                            Icon = "🧩",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Modules",
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoutePath = "/modules",
                            ShowInMobile = false
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage regions",
                            DisplayOrder = 2,
                            Icon = "🗺️",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Region Master",
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoutePath = "/regions",
                            ShowInMobile = false
                        },
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage festivals by year",
                            DisplayOrder = 3,
                            Icon = "🎉",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Festivals",
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoutePath = "/festivals",
                            ShowInMobile = true
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage deities / gods",
                            DisplayOrder = 4,
                            Icon = "🛕",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Deities",
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoutePath = "/deities",
                            ShowInMobile = true
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage chants",
                            DisplayOrder = 5,
                            Icon = "📿",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Chants",
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoutePath = "/chants",
                            ShowInMobile = true
                        },
                        new
                        {
                            Id = new Guid("bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Manage languages and their regions",
                            DisplayOrder = 6,
                            Icon = "🗣️",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Languages",
                            ParentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            RoutePath = "/languages",
                            ShowInMobile = true
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Application configuration",
                            DisplayOrder = 3,
                            Icon = "⚙️",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Configuration",
                            ShowInMobile = false
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Configure chants under each chant category",
                            DisplayOrder = 1,
                            Icon = "📜",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Chants Config",
                            ParentId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RoutePath = "/chants-config",
                            ShowInMobile = true
                        },
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Daily Panchangam by region and location",
                            DisplayOrder = 2,
                            Icon = "🗓️",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Panchangam",
                            ParentId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RoutePath = "/panchangam",
                            ShowInMobile = true
                        },
                        new
                        {
                            Id = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Daily spiritual practice",
                            DisplayOrder = 4,
                            Icon = "🙏",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Sadhana",
                            ShowInMobile = true
                        },
                        new
                        {
                            Id = new Guid("eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Recommended chants for today and your japa practice",
                            DisplayOrder = 1,
                            Icon = "🪷",
                            IsActive = true,
                            IsVisibleInMenu = true,
                            Name = "Today's Sadhana",
                            ParentId = new Guid("dddddddd-dddd-dddd-dddd-dddddddddddd"),
                            RoutePath = "/sadhana",
                            ShowInMobile = true
                        });
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.Panchangam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AbhijitMuhurtham")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("AmruthaKalam")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Ayanam")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Durmuhurtham")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Gulika")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Masam")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NakshatramDetails")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Paksham")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("RahuKalam")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("RegionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Rutuvu")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("SakaSamvatsaram")
                        .HasColumnType("integer");

                    b.Property<TimeOnly?>("Sunrise")
                        .HasColumnType("time without time zone");

                    b.Property<TimeOnly?>("Sunset")
                        .HasColumnType("time without time zone");

                    b.Property<string>("TeluguSamvatsaram")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("TithiDetails")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Varjyam")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int?>("VikramaSamvatsaram")
                        .HasColumnType("integer");

                    b.Property<string>("Yamagandam")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.HasIndex("Date", "RegionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Panchangams_Date_Region");

                    b.HasIndex("Year", "RegionId")
                        .HasDatabaseName("IX_Panchangams_Year_Region");

                    b.ToTable("Panchangams", (string)null);
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Regions_Name");

                    b.ToTable("Regions", (string)null);
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_RoleName");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "System administrator with full privileges",
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Spiritual seeker role aligned with Hindu Dharma values",
                            RoleName = "Sanathan"
                        });
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.SadhanaLog", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ChantConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("ChantName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<string>("DeityName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("MalasCompleted")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TargetCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasRecommended")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ChantConfigId");

                    b.HasIndex("UserId", "Date")
                        .HasDatabaseName("IX_SadhanaLogs_User_Date");

                    b.HasIndex("UserId", "Date", "ChantConfigId")
                        .IsUnique()
                        .HasDatabaseName("UX_SadhanaLogs_User_Date_Chant");

                    b.ToTable("SadhanaLogs", (string)null);
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.SadhanaStreak", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("LastPracticeDate")
                        .HasColumnType("date");

                    b.Property<int>("LongestStreak")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TotalDaysPracticed")
                        .HasColumnType("integer");

                    b.Property<int>("TotalMalas")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_SadhanaStreaks_User");

                    b.ToTable("SadhanaStreaks", (string)null);
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ModifiedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<string>("SeekerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedBy = "system",
                            CreatedDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin",
                            FullName = "Administrator",
                            MobileNumber = "0000000000",
                            PasswordHash = "$2a$11$IcC0k9qwHgoBzVuv369tC.z4bukAlUY7IxbpbLD4MU7At7TX4Sxsi",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.ChantConfig", b =>
                {
                    b.HasOne("Sanathana.Companion.Domain.Entities.Chant", "Chant")
                        .WithMany()
                        .HasForeignKey("ChantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chant");
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.ChantConfigAudio", b =>
                {
                    b.HasOne("Sanathana.Companion.Domain.Entities.ChantConfig", "ChantConfig")
                        .WithOne("Audio")
                        .HasForeignKey("Sanathana.Companion.Domain.Entities.ChantConfigAudio", "ChantConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChantConfig");
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.MenuModule", b =>
                {
                    b.HasOne("Sanathana.Companion.Domain.Entities.MenuModule", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.Panchangam", b =>
                {
                    b.HasOne("Sanathana.Companion.Domain.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.SadhanaLog", b =>
                {
                    b.HasOne("Sanathana.Companion.Domain.Entities.ChantConfig", "ChantConfig")
                        .WithMany()
                        .HasForeignKey("ChantConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChantConfig");
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.User", b =>
                {
                    b.HasOne("Sanathana.Companion.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.ChantConfig", b =>
                {
                    b.Navigation("Audio");
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.MenuModule", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("Sanathana.Companion.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
